package adb

import "testing"

// pythonShlexGolden was generated by running CPython 3's shlex.quote over the
// case list below, then the phone_type composition
// shlex.quote(text.replace("%", "%25").replace(" ", "%s")).
//
// It is the cross-check the hand-written table in quote_test.go cannot be: those
// expectations were reasoned about, these were measured. The escapedQuoted
// column is the one that matters most — it is the literal argv element
// `input text ...` receives, and getting the escape ORDER or the ASCII-only safe
// set wrong is what silently breaks Chinese and spaces on a real device.
//
// Regenerate with:
//
//	python3 -c 'import shlex; print(shlex.quote(<case>))'
var pythonShlexGolden = []struct{ in, quoted, escapedQuoted string }{
	{"", "''", "''"},
	{"hello", "hello", "hello"},
	{"hello world", "'hello world'", "hello%sworld"},
	{"你好", "'你好'", "'你好'"},
	{"你好世界", "'你好世界'", "'你好世界'"},
	{"😀", "'😀'", "'😀'"},
	{"a'b", "'a'\"'\"'b'", "'a'\"'\"'b'"},
	{"a\"b", "'a\"b'", "'a\"b'"},
	{"a'b\"c", "'a'\"'\"'b\"c'", "'a'\"'\"'b\"c'"},
	{"$(whoami)", "'$(whoami)'", "'$(whoami)'"},
	{"`id`", "'`id`'", "'`id`'"},
	{"a&&b", "'a&&b'", "'a&&b'"},
	{"a||b", "'a||b'", "'a||b'"},
	{"a;b", "'a;b'", "'a;b'"},
	{"a|b", "'a|b'", "'a|b'"},
	{"a>b", "'a>b'", "'a>b'"},
	{"a<b", "'a<b'", "'a<b'"},
	{"a\nb", "'a\nb'", "'a\nb'"},
	{"a\tb", "'a\tb'", "'a\tb'"},
	{"a\\b", "'a\\b'", "'a\\b'"},
	{"~user", "'~user'", "'~user'"},
	{"*", "'*'", "'*'"},
	{"?", "'?'", "'?'"},
	{"[a]", "'[a]'", "'[a]'"},
	{"{a}", "'{a}'", "'{a}'"},
	{"#comment", "'#comment'", "'#comment'"},
	{"!bang", "'!bang'", "'!bang'"},
	{"^caret", "'^caret'", "'^caret'"},
	{"%", "%", "%25"},
	{"%s", "%s", "%25s"},
	{"100%", "100%", "100%25"},
	{"a b%c", "'a b%c'", "a%sb%25c"},
	{"_@%+=:,./-", "_@%+=:,./-", "_@%25+=:,./-"},
	{"ABCabc123", "ABCabc123", "ABCabc123"},
	{"-flag", "-flag", "-flag"},
	{"--flag=value", "--flag=value", "--flag=value"},
	{"path/to/file.txt", "path/to/file.txt", "path/to/file.txt"},
	{"a:b,c.d/e-f", "a:b,c.d/e-f", "a:b,c.d/e-f"},
	{" leading", "' leading'", "%sleading"},
	{"trailing ", "'trailing '", "trailing%s"},
	{"  ", "'  '", "%s%s"},
	{"\x00", "'\x00'", "'\x00'"},
	{"\x7f", "'\x7f'", "'\x7f'"},
	{"中文 with space", "'中文 with space'", "'中文%swith%sspace'"},
	{"emoji😀space ", "'emoji😀space '", "'emoji😀space%s'"},
	{"'", "''\"'\"''", "''\"'\"''"},
	{"''", "''\"'\"''\"'\"''", "''\"'\"''\"'\"''"},
	{"'''", "''\"'\"''\"'\"''\"'\"''", "''\"'\"''\"'\"''\"'\"''"},
	{"\\'", "'\\'\"'\"''", "'\\'\"'\"''"},
	{"a'''b", "'a'\"'\"''\"'\"''\"'\"'b'", "'a'\"'\"''\"'\"''\"'\"'b'"},
}

func TestQuoteMatchesRealPythonShlexGolden(t *testing.T) {
	for _, tc := range pythonShlexGolden {
		if got := Quote(tc.in); got != tc.quoted {
			t.Errorf("Quote(%q) = %q, CPython shlex.quote = %q", tc.in, got, tc.quoted)
		}
		if got := Quote(EscapeInputText(tc.in)); got != tc.escapedQuoted {
			t.Errorf("Quote(EscapeInputText(%q)) = %q, CPython = %q", tc.in, got, tc.escapedQuoted)
		}
	}
}
